name: messages_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_value: ^8.1.2
  built_collection: ^5.1.1
  connectivity_plus: ^1.4.0
  chopper: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  provider: ^6.0.1

dev_dependencies:
  build_runner: ^2.1.4
  built_value_generator: ^8.0.4
  chopper_generator: ^4.0.2
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1

flutter:

  uses-material-design: true

flutter_intl:
  enabled: false
  main_locale: en
  class_name: I18n